# Checkout code on every commit to the main branch
# Path: .github/workflows/run.yaml
name: Run Challenge Answers
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  run-answers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Execute challenge answer scripts
        run: |
          make run | tee /tmp/aoc2022-mathew-fleisch-answers.txt
          make zip-log
      - uses: actions/upload-artifact@v2
        with:
          name: aoc2022-mathew-fleisch-answers.txt
          path: /tmp/aoc2022-mathew-fleisch-answers.txt
      - uses: actions/upload-artifact@v2
        with:
          name: aoc2022-mathew-fleisch-logs.zip
          path: /tmp/aoc2022-mathew-fleisch-logs.zip