# Checkout code on every commit to the main branch
# Path: .github/workflows/run.yaml
name: Run Challenge Answers
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  run-answers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute challenge answer scripts
        env:
          SKIP_LONG: 1
        run: |
          make docker-run | tee /tmp/aoc2022-mathew-fleisch-answers.txt
          make zip-log
      - uses: actions/upload-artifact@v3
        with:
          name: aoc2022-mathew-fleisch-answers.txt
          path: /tmp/aoc2022-mathew-fleisch-answers.txt
      - uses: actions/upload-artifact@v3
        with:
          name: aoc2022-mathew-fleisch-logs.zip
          path: /tmp/aoc2022-mathew-fleisch-logs.zip